# Generated by Django 5.1.4 on 2024-12-13 03:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_si', models.CharField(blank=True, max_length=100)),
                ('name_ta', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'valuation_make',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NumberPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=15, unique=True)),
                ('purpose', models.CharField(choices=[('0', 'Selling'), ('1', 'Buying')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceDetails',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_si', models.CharField(blank=True, max_length=100)),
                ('name_ta', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='vehicle_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('store', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=25)),
                ('make', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('edition', models.CharField(max_length=25)),
                ('year', models.CharField(max_length=25)),
                ('milage', models.CharField(max_length=25)),
                ('fuel_type', models.CharField(max_length=25)),
                ('gear', models.CharField(max_length=25)),
                ('engine_capacity', models.CharField(max_length=25)),
                ('condition', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=25)),
                ('options', models.CharField(max_length=25)),
                ('posted_date', models.CharField(max_length=25)),
                ('scraped_date', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_processed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('mileage', models.CharField(max_length=100)),
                ('gear', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('engine_capability', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('scraped_date', models.CharField(max_length=100)),
                ('store', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='propertydetails',
            old_name='description',
            new_name='perches',
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_details',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_features',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='property_type',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='unit_price',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='website',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CityDetails',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_si', models.CharField(max_length=100)),
                ('name_ta', models.CharField(max_length=100)),
                ('sub_name_en', models.CharField(max_length=100)),
                ('sub_name_si', models.CharField(max_length=100)),
                ('sub_name_ta', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('city_district_id', models.ForeignKey(db_column='district_id', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='landapp.districtdetails')),
            ],
            options={
                'db_table': 'cities',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='MakeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landapp.make')),
            ],
            options={
                'db_table': 'valuation_model',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='districtdetails',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landapp.provincedetails'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('0', 'Selling'), ('1', 'Buying')], max_length=20)),
                ('year', models.IntegerField(blank=True, choices=[('', 'Select Year'), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], null=True, validators=[django.core.validators.MinValueValidator(1900, 'Insert a valid year'), django.core.validators.MaxValueValidator(2030, 'Insert a valid year')], verbose_name='year')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landapp.make')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landapp.makemodel')),
            ],
        ),
    ]
