# Generated by Django 5.1.4 on 2024-12-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landapp', '0003_delete_numberplate_remove_vehicle_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
