# Generated by Django 4.1.13 on 2025-03-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landapp', '0004_alter_make_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_processed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('mileage', models.CharField(max_length=100)),
                ('gear', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('engine_capability', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('scraped_date', models.CharField(max_length=100)),
                ('store', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('cleaned_details', models.CharField(max_length=100)),
                ('number_of_owners', models.CharField(max_length=100)),
                ('registration_year', models.CharField(max_length=100)),
                ('selling_condition', models.CharField(max_length=100)),
                ('modification_status', models.CharField(max_length=100)),
            ],
        ),
    ]
