# Generated by Django 4.1.13 on 2025-03-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landapp', '0005_vehicle_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('valuation_make', models.CharField(max_length=100)),
                ('valuation_model', models.CharField(max_length=100)),
                ('valuation_year', models.CharField(max_length=10)),
                ('valuation_purpose', models.CharField(max_length=100)),
                ('valuation_mileage', models.CharField(max_length=100)),
                ('valuation_gear', models.CharField(max_length=100)),
                ('valuation_engine_capacity', models.CharField(max_length=100)),
                ('valuation_fuel', models.CharField(max_length=100)),
                ('valuation_owners', models.CharField(max_length=100)),
                ('valuation_selling_condition', models.CharField(max_length=100)),
                ('valuation_modification', models.CharField(max_length=100)),
                ('valuation_avg_price', models.CharField(max_length=10)),
                ('valuation_max_price', models.CharField(max_length=10)),
                ('valuation_min_price', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vehicle_feedback',
            },
        ),
        migrations.CreateModel(
            name='LandValuationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('feedback', models.TextField()),
                ('valuation_district', models.CharField(max_length=100)),
                ('valuation_city', models.CharField(max_length=100)),
                ('valuation_map_district', models.CharField(max_length=100)),
                ('valuation_map_city', models.CharField(max_length=100)),
                ('valuation_property_type', models.CharField(max_length=100)),
                ('valuation_bedrooms', models.CharField(max_length=100)),
                ('valuation_bathrooms', models.CharField(max_length=100)),
                ('valuation_floor_area', models.CharField(max_length=100)),
                ('valuation_land_area', models.CharField(max_length=100)),
                ('valuation_comfort_features', models.CharField(max_length=100)),
                ('valuation_max_value', models.CharField(max_length=10)),
                ('valuation_avg_value', models.CharField(max_length=10)),
                ('valuation_min_value', models.CharField(max_length=10)),
                ('valuation_avg_rent_value', models.CharField(max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'real_estate_feedback',
            },
        ),
    ]
